/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as token from './token';
export type { token };
export type { HouseRegistry } from './HouseRegistry';
export type { HouseRegistryExt } from './HouseRegistryExt';
