/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as houseRegistrySol from "./HouseRegistry.sol";
export type { houseRegistrySol };
import type * as token from "./token";
export type { token };
export type { Greeter } from "./Greeter";
export type { HouseRegistryExt } from "./HouseRegistryExt";
