/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { HouseRegistry__factory } from './HouseRegistry__factory';
export { TokenIntarface__factory } from './TokenIntarface__factory';
