/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { HouseRegistry } from './HouseRegistry';
export type { TokenIntarface } from './TokenIntarface';
