/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { HouseNFT } from './HouseNFT';
export type { IHouseNFT } from './IHouseNFT';
export type { Token } from './Token';
